name: valides_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.0
  syncfusion_flutter_pdfviewer: ^29.1.41
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.4.0
  table_calendar: ^3.0.0
  shared_preferences: ^2.0.0
  http: ^1.4.0
  sqflite: ^2.0.0+4
  path: ^1.8.0
  provider: ^6.0.5
  file_picker: ^10.1.4
  flutter_gemini: ^3.0.0
  pdf_render: ^1.4.12
  flutter_cache_manager: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/pdf/
    - lib/conteudo/
