name: alugaix_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.4.0
  table_calendar: ^3.0.0
  shared_preferences: ^2.0.0
  charts_flutter: ^0.12.0
  fl_chart: ^0.40.0
  syncfusion_flutter_charts: ^20.2.42
  http: ^0.13.3
  sqflite: ^2.0.0+4
  path: ^1.8.0
  provider: ^6.0.5
  file_picker: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/

  